
  CREATE OR REPLACE PROCEDURE "SCOTT"."ADD_ACTIVITY_MASTER" 
(
  ACT_TYPE IN VARCHAR2  
, ACT_NAME IN VARCHAR2  
, ACT_FOR IN VARCHAR2  
, ACT_DUE_DATE IN VARCHAR2  
, ACT_DUE_MONTH IN VARCHAR2  
, ACT_DUE_YEAR IN VARCHAR2  
, ACT_DETAIL IN VARCHAR2  
, ACT_LEADER IN VARCHAR2  
, ACT_MEMBER IN VARCHAR2  
) AS 
BEGIN
  insert into activity_master (Act_type,Act_name,Act_for,Act_due_date,Act_due_month,Act_due_year,Act_detail,Act_leader,Act_member) values(ACT_TYPE,ACT_NAME,ACT_FOR,ACT_DUE_DATE,ACT_DUE_MONTH,ACT_DUE_YEAR,ACT_DETAIL,ACT_LEADER,ACT_MEMBER);
END ADD_ACTIVITY_MASTER;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."ADD_CLIENT_MASTER" 
(
  CL_FIRST_NAME IN VARCHAR2  
, CL_MIDDLE_NAME IN VARCHAR2  
, CL_LAST_NAME IN VARCHAR2 
, CL_COMPANY_ID IN INTEGER
, CL_COMPANY_NAME IN VARCHAR2  
, CL_PHONE_NO IN INTEGER  
, CL_EMAIL_ID IN VARCHAR2
) AS 
BEGIN
  insert into client_master (Cl_first_name,Cl_middle_name,Cl_last_name,CL_COMPANY_ID,Cl_company_name,Cl_phone_no,Cl_email_ID) values (CL_FIRST_NAME,CL_MIDDLE_NAME,CL_LAST_NAME,CL_COMPANY_ID,CL_COMPANY_NAME,CL_PHONE_NO,CL_EMAIL_ID);
END ADD_CLIENT_MASTER;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."ADD_COMPANY_MASTER" 
(
  C_NAME IN VARCHAR2  
, C_PHONE_NO IN INTEGER  
, C_EMAIL_ID IN VARCHAR2  
, C_ADDRESS IN VARCHAR2  
, C_CITY IN VARCHAR2  
, C_STATE IN VARCHAR2  
, C_COUNTRY IN VARCHAR2  
) AS 
BEGIN
  insert into company_master (C_name,C_phone_no,C_email_ID,C_address,C_city,C_state,C_country) values (C_NAME,C_PHONE_NO,C_EMAIL_ID,C_ADDRESS,C_CITY,C_STATE,C_COUNTRY);
END ADD_COMPANY_MASTER;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."ADD_DEPT_MASTER" (NAME IN VARCHAR2, DESCRIPTION IN VARCHAR2) AS 
BEGIN
  insert into dept_master(Name,Description) values(NAME,DESCRIPTION);
END ADD_DEPT_MASTER;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."ADD_DESIG_MASTER" 
(
  NAME IN VARCHAR2  
, DESCRIPTION IN VARCHAR2  
) AS 
BEGIN
  insert into desig_master(Name,Description) values(NAME,DESCRIPTION);
END ADD_DESIG_MASTER;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."ADD_LEAD_MASTER" 
(
  LEAD_TYPE IN VARCHAR2  
, LEAD_SALESMAN IN VARCHAR2 
, LEAD_CLIENT IN VARCHAR2 
, LEAD_DUE_DATE IN VARCHAR2  
, LEAD_DUE_MONTH IN VARCHAR2  
, LEAD_DUE_YEAR IN VARCHAR2  
, LEAD_DETAIL IN VARCHAR2  
) AS 
BEGIN
  insert into lead_master (Lead_type,Lead_salesman,Lead_client,Lead_due_date,Lead_due_month,Lead_due_year,Lead_detail) values (LEAD_TYPE,LEAD_SALESMAN,LEAD_CLIENT,LEAD_DUE_DATE,LEAD_DUE_MONTH,LEAD_DUE_YEAR,LEAD_DETAIL);
END ADD_LEAD_MASTER;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."ADD_PREV_SALES_MASTER" 
(
  S_ID IN NUMBER  
, TARGET IN VARCHAR2  
, TARGET_DUE_DATE IN VARCHAR2  
, TARGET_DUE_MONTH IN VARCHAR2  
, TARGET_DUE_YEAR IN VARCHAR2  
, STATUS IN VARCHAR2  
) AS 
BEGIN
  insert into prev_sales_master (S_id,Target,Target_due_date,Target_due_month,Target_due_year,Status) values (S_ID,TARGET,TARGET_DUE_DATE,TARGET_DUE_MONTH,TARGET_DUE_YEAR,STATUS);
END ADD_PREV_SALES_MASTER;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."ADD_PRODUCT_MASTER" 
(
  NAME IN VARCHAR2  
, QUANTITY IN NUMBER  
) AS 
BEGIN
  INSERT INTO PRODUCT_MASTER(NAME,QUANTITY) VALUES(NAME,QUANTITY);
END ADD_PRODUCT_MASTER;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."ADD_SALESMAN_MASTER" 
(
  FIRST_NAME IN VARCHAR2  
, MIDDLE_NAME IN VARCHAR2  
, LAST_NAME IN VARCHAR2  
, USERNAME IN VARCHAR2  
, PASSWORD IN VARCHAR2  
, GENDER IN VARCHAR2  
, BIRTHDATE_DAY IN VARCHAR2  
, BIRTHDATE_MONTH IN VARCHAR2  
, BIRTHDATE_YEAR IN VARCHAR2  
, DEPARTMENT IN VARCHAR2  
, PHONE_NO IN NUMBER  
, EMAIL_ID IN VARCHAR2  
, ADDRESS IN VARCHAR2  
, UNDER IN VARCHAR2  
, PHOTO IN VARCHAR2    
) AS 
BEGIN
  insert into salesman_master (First_name,Middle_name,Last_name,Username,Password,Gender,Birthdate_day,Birthdate_month,Birthdate_year,Department,Phone_no,Email_ID,Address,Under,Photo) values(FIRST_NAME,MIDDLE_NAME,LAST_NAME,USERNAME,PASSWORD,GENDER,BIRTHDATE_DAY,BIRTHDATE_MONTH,BIRTHDATE_YEAR,DEPARTMENT,PHONE_NO,EMAIL_ID,ADDRESS,UNDER,PHOTO);
END ADD_SALESMAN_MASTER;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."ADD_SALESMANAGER_MASTER" 
(
  FIRST_NAME IN VARCHAR2  
, MIDDLE_NAME IN VARCHAR2  
, LAST_NAME IN VARCHAR2  
, USERNAME IN VARCHAR2  
, PASSWORD IN VARCHAR2  
, GENDER IN VARCHAR2  
, BIRTHDATE_DAY IN VARCHAR2  
, BIRTHDATE_MONTH IN VARCHAR2  
, BIRTHDATE_YEAR IN VARCHAR2  
, DEPARTMENT IN VARCHAR2  
, PHONE_NO IN NUMBER  
, EMAIL_ID IN VARCHAR2  
, ADDRESS IN VARCHAR2  
, PHOTO IN VARCHAR2  
) AS 
BEGIN
  insert into salesmanager_master(First_name,Middle_name,Last_name,Username,Password,Gender,Birthdate_day,Birthdate_month,Birthdate_year,Department,Phone_no,Email_ID,Address,Photo) values(FIRST_NAME,MIDDLE_NAME,LAST_NAME,USERNAME,PASSWORD,GENDER,BIRTHDATE_DAY,BIRTHDATE_MONTH,BIRTHDATE_YEAR,DEPARTMENT,PHONE_NO,EMAIL_ID,ADDRESS,PHOTO);
END ADD_SALESMANAGER_MASTER;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."ADD_STOCK_MASTER" 
(
  SMAN IN VARCHAR2  
, CL IN VARCHAR2
, PRODNAME IN VARCHAR2 
, QTY IN NUMBER  
, DAY IN VARCHAR2  
, MONTH IN VARCHAR2  
, YEAR IN VARCHAR2   
) AS 
BEGIN
  insert into stock_master (Sman,Cl,prodname,Qty,Day,Month,Year) values (SMAN,CL,PRODNAME,QTY,DAY,MONTH,YEAR);
END ADD_STOCK_MASTER;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."ADMIN_LOGIN" 
(
  usernm IN VARCHAR2
, UNAME OUT VARCHAR2  
, PASS OUT VARCHAR2  
) AS 
BEGIN
  select USERNAME into UNAME from ADMIN_MASTER where USERNAME = usernm;
  SELECT PASSWORD INTO PASS FROM ADMIN_MASTER where USERNAME = usernm;
END ADMIN_LOGIN;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."ASSIGN_TARGET" 
(
  TG IN VARCHAR2  
, DATE_DAY IN VARCHAR2  
, DATE_MONTH IN VARCHAR2  
, DATE_YEAR IN VARCHAR2
, salesman IN VARCHAR2
) AS 
BEGIN
  UPDATE salesman_master SET target = TG, due_date_day = DATE_DAY, due_date_month = DATE_MONTH, due_date_year = DATE_YEAR WHERE username = salesman;
END ASSIGN_TARGET;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."ASSIGN_UPDATE_TARGET" 
(
   salesman IN VARCHAR2
) AS 
BEGIN
  INSERT INTO prev_sales_master (s_id, target, target_due_date, target_due_month, target_due_year, status) SELECT s.id, s.target, s.due_date_day, s.due_date_month, s.due_date_year,(s.target_status - s.target) FROM salesman_master s WHERE s.username = salesman;
END ASSIGN_UPDATE_TARGET;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."DELETE_ACTIVITY" 
(
  ACTIVITY_NAME IN VARCHAR2  
) AS 
BEGIN
  delete from activity_master where act_name = ACTIVITY_NAME;
END DELETE_ACTIVITY;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."DELETE_COMPANY" 
(
  CNAME IN VARCHAR2  
) AS 
BEGIN
  delete from company_master where C_NAME = CNAME;
END DELETE_COMPANY;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."DELETE_DEPT" 
(
  DEPT_NAME IN VARCHAR2  
) AS 
BEGIN
  delete from dept_master where Name = dept_name;
END DELETE_DEPT;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."DELETE_DESIG" 
(
  DESIG_NAME IN VARCHAR2  
) AS 
BEGIN
  delete from desig_master where Name = desig_name;
END DELETE_DESIG;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."DELETE_LEAD" 
(
  LEAD_TYPE IN VARCHAR2
, LEAD_SALESMAN IN VARCHAR2
, LEAD_CLIENT IN VARCHAR2
) AS 
BEGIN
  delete from lead_master where lead_type = LEAD_TYPE and lead_salesman = LEAD_SALESMAN and lead_client = LEAD_CLIENT;
END DELETE_LEAD;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."DELETE_MANAGER" 
(
  UNAME IN VARCHAR2  
) AS 
BEGIN
  delete from salesmanager_master where username = UNAME;
END DELETE_MANAGER;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."DELETE_PERSON" 
(
  UNAME IN VARCHAR2  
) AS 
BEGIN
  delete from salesman_master where username = UNAME;
END DELETE_PERSON;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."DELETE_PROD" 
(
  NM IN VARCHAR2  
) AS 
BEGIN
  delete from product_master where Name = nm;
END DELETE_PROD;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."GET_COMPANY_ID" 
(
  company_name IN VARCHAR2
,  company_id OUT NUMBER 
) AS 
BEGIN
  select c_id INTO company_id from company_master where c_name = company_name;
END GET_COMPANY_ID;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."MANAGER_LOGIN" 
(
  usernm IN VARCHAR2
, MUNAME OUT VARCHAR2  
, MPASS OUT VARCHAR2  
) AS 
BEGIN
  select USERNAME into MUNAME from SALESMANAGER_MASTER where USERNAME = usernm;
  SELECT PASSWORD INTO MPASS FROM SALESMANAGER_MASTER where USERNAME = usernm;
END MANAGER_LOGIN;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."SALES_PERSON_LOGIN" 
(
  UNM IN VARCHAR2  
, UNAME OUT VARCHAR2  
, PASS OUT VARCHAR2  
) AS 
BEGIN
  select USERNAME into UNAME from SALESMAN_MASTER where USERNAME = unm;
  SELECT PASSWORD INTO PASS FROM SALESMAN_MASTER where USERNAME = unm;
END SALES_PERSON_LOGIN;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."SELECT_DEPT" 
(
  NM IN VARCHAR2  
, GETNAME OUT VARCHAR2  
, GETDESC OUT VARCHAR2  
) AS 
BEGIN
  select Name into GetName from Dept_Master where Name = Nm;
  select DESCRIPTION into GetDesc from Dept_Master where Name = Nm;
END SELECT_DEPT;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."SELECT_DESIG" 
(
  NM IN VARCHAR2  
, GETNAME OUT VARCHAR2  
, GETDESC OUT VARCHAR2  
) AS 
BEGIN
  select Name into GetName from Desig_Master where Name = Nm;
  select DESCRIPTION into GetDesc from Desig_Master where Name = Nm;
END SELECT_DESIG;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."SELECT_PROD" 
(
  NM IN VARCHAR2  
, GETNAME OUT VARCHAR2  
) AS 
BEGIN
  select Name into GetName from Product_Master where Name = Nm;
END SELECT_PROD;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."UPDATE_CLIENT" 
(
  PREVEMAIL IN VARCHAR2  
, CURREMAIL IN VARCHAR2  
, PHNO IN NUMBER
) AS 
BEGIN
  update client_master set CL_PHONE_NO = PHNO, CL_EMAIL_ID = CURREMAIL where CL_EMAIL_ID = PREVEMAIL;
END UPDATE_CLIENT;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."UPDATE_COMPANY" 
(
  PREVNAME IN VARCHAR2  
, CURRNAME IN VARCHAR2  
, PHNO IN NUMBER
, EMAIL IN VARCHAR2
) AS 
BEGIN
  update company_master set C_NAME = CURRNAME, C_PHONE_NO = PHNO, C_EMAIL_ID = EMAIL where C_NAME = PREVNAME;
END UPDATE_COMPANY;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."UPDATE_DEPT" 
(
  PREVNAME IN VARCHAR2  
, CURRNAME IN VARCHAR2  
, CURRDESC IN VARCHAR2  
) AS 
BEGIN
  update dept_master set Name = CURRNAME, Description = CURRDESC where Name = PREVNAME;
END UPDATE_DEPT;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."UPDATE_DESIG" 
(
  PREVNAME IN VARCHAR2  
, CURRNAME IN VARCHAR2  
, CURRDESC IN VARCHAR2  
) AS 
BEGIN
  update desig_master set Name = CURRNAME, Description = CURRDESC where Name = PREVNAME;
END UPDATE_DESIG;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."UPDATE_MANAGER" 
(
  UNM IN VARCHAR2  
, FNAME IN VARCHAR2  
, MNAME IN VARCHAR2  
, LNAME IN VARCHAR2  
, BDATE IN VARCHAR2  
, BMON IN VARCHAR2  
, BYEAR IN VARCHAR2  
, PHONENO IN NUMBER  
, EMAIL IN VARCHAR2  
, ADDR IN VARCHAR2  
, PIC IN VARCHAR2  
) AS 
BEGIN
  update salesmanager_master set first_name = FNAME,middle_name = MNAME,last_name = LNAME,Birthdate_day = BDATE,Birthdate_month = BMON,Birthdate_year = BYEAR,PHONE_NO = phoneno,EMAIL_ID = EMAIL,ADDRESS = ADDR,PHOTO=pic where username = UNM;
END UPDATE_MANAGER;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."UPDATE_PERSON" 
(
  UNM IN VARCHAR2  
, FNAME IN VARCHAR2  
, MNAME IN VARCHAR2  
, LNAME IN VARCHAR2  
, BDATE IN VARCHAR2  
, BMON IN VARCHAR2  
, BYEAR IN VARCHAR2  
, PHONENO IN NUMBER  
, EMAIL IN VARCHAR2  
, ADDR IN VARCHAR2  
, PIC IN VARCHAR2  
) AS 
BEGIN
  update salesman_master set first_name = FNAME,middle_name = MNAME,last_name = LNAME,Birthdate_day = BDATE,Birthdate_month = BMON,Birthdate_year = BYEAR,PHONE_NO = phoneno,EMAIL_ID = EMAIL,ADDRESS = ADDR,PHOTO=pic where username = UNM;
END UPDATE_PERSON;
/
 

  CREATE OR REPLACE PROCEDURE "SCOTT"."UPDATE_PROD" 
(
  PREVNAME IN VARCHAR2  
, CURRNAME IN VARCHAR2  
) AS 
BEGIN
  update product_master set Name = CURRNAME where Name = PREVNAME;
END UPDATE_PROD;
/
 
